<?php
namespace App\Core;

class Controller
{
    public static function render(string $viewPath, array $data = []): void
    {
        extract($data); // ex: $title, $content
        
        // send output generated by script to a buffer (to validate, modify, etc + increased performances)
        ob_start();
        require __DIR__ . '/../Views/' . $viewPath . '.php';
        $content = ob_get_clean(); // get output and clean buffer
        require __DIR__ . '/../Views/layout.php';
    }
}
